from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ....models.tfl.api.presentation.entities.line import Line
    from .item.with_start_date_item_request_builder import WithStartDateItemRequestBuilder

class StatusRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /Line/{ids-id}/Status
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new StatusRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/Line/{ids%2Did}/Status{?detail*}", path_parameters)
    
    def by_start_date(self,start_date: str) -> WithStartDateItemRequestBuilder:
        """
        Gets an item from the tfl_api.Line.item.Status.item collection
        param start_date: Unique identifier of the item
        Returns: WithStartDateItemRequestBuilder
        """
        if start_date is None:
            raise TypeError("start_date cannot be null.")
        from .item.with_start_date_item_request_builder import WithStartDateItemRequestBuilder

        url_tpl_params = get_path_parameters(self.path_parameters)
        url_tpl_params["StartDate"] = start_date
        return WithStartDateItemRequestBuilder(self.request_adapter, url_tpl_params)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[StatusRequestBuilderGetQueryParameters]] = None) -> Optional[list[Line]]:
        """
        Gets the line status of for given line ids e.g Minor Delays
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[list[Line]]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from ....models.tfl.api.presentation.entities.line import Line

        return await self.request_adapter.send_collection_async(request_info, Line, None)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[StatusRequestBuilderGetQueryParameters]] = None) -> RequestInformation:
        """
        Gets the line status of for given line ids e.g Minor Delays
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> StatusRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: StatusRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return StatusRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class StatusRequestBuilderGetQueryParameters():
        """
        Gets the line status of for given line ids e.g Minor Delays
        """
        # Include details of the disruptions that are causing the line status including the affected stops and routes
        detail: Optional[bool] = None

    
    @dataclass
    class StatusRequestBuilderGetRequestConfiguration(RequestConfiguration[StatusRequestBuilderGetQueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

