from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ...models.tfl.api.presentation.entities.charge_connector_occupancy import ChargeConnectorOccupancy
    from .item.with_ids_item_request_builder import WithIdsItemRequestBuilder

class ChargeConnectorRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /Occupancy/ChargeConnector
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new ChargeConnectorRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/Occupancy/ChargeConnector", path_parameters)
    
    def by_ids(self,ids: str) -> WithIdsItemRequestBuilder:
        """
        Gets an item from the tfl_api.Occupancy.ChargeConnector.item collection
        param ids: Unique identifier of the item
        Returns: WithIdsItemRequestBuilder
        """
        if ids is None:
            raise TypeError("ids cannot be null.")
        from .item.with_ids_item_request_builder import WithIdsItemRequestBuilder

        url_tpl_params = get_path_parameters(self.path_parameters)
        url_tpl_params["ids"] = ids
        return WithIdsItemRequestBuilder(self.request_adapter, url_tpl_params)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[list[ChargeConnectorOccupancy]]:
        """
        Gets the occupancy for all charge connectors
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[list[ChargeConnectorOccupancy]]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from ...models.tfl.api.presentation.entities.charge_connector_occupancy import ChargeConnectorOccupancy

        return await self.request_adapter.send_collection_async(request_info, ChargeConnectorOccupancy, None)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Gets the occupancy for all charge connectors
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> ChargeConnectorRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: ChargeConnectorRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return ChargeConnectorRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class ChargeConnectorRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

